import { CreatePermissionDto } from "src/permission/dto/create-permission.dto";

export const permissions: CreatePermissionDto[] = [
    { name: "CREATE_CATEGORY" },
    { name: "CREATE_MANY_CATEGORIES" },
    { name: "UPDATE_CATEGORY" },
    { name: "DELETE_CATEGORY" },
    { name: "CREATE_ADDITION" },
    { name: "UPDATE_ADDITION" },
    { name: "DELETE_ADDITION" },
    { name: "CREATE_NOVELTY" },
    { name: "UPDATE_NOVELTY" },
    { name: "DELETE_NOVELTY" },
    { name: "CREATE_OFFER" },
    { name: "UPDATE_OFFER" },
    { name: "DELETE_OFFER" },
    { name: "CREATE_ORDER" },
    { name: "UPDATE_ORDER" },
    { name: "DELETE_ORDER" },
    { name: "CREATE_PERMISSION" },
    { name: "CREATE_MANY_PERMISSIONS" },
    { name: "UPDATE_PERMISSION" },
    { name: "DELETE_PERMISSION" },
    { name: "CREATE_ROLE" },
    { name: "CREATE_MANY_ROLES" },
    { name: "UPDATE_ROLE" },
    { name: "DELETE_ROLE" },
    { name: "CREATE_SWEET" },
    { name: "UPDATE_SWEET" },
    { name: "DELETE_SWEET" },
    { name: "CREATE_USER" },
    { name: "UPDATE_USER" },
    { name: "DELETE_USER" },
    { name: "FIND_ONE_ORDER_BY_ID" },
    { name: "FIND_ONE_PERMISSION_BY_ID" },
    { name: "FIND_ONE_ROLE_BY_ID" },
    { name: "FIND_ONE_USER_BY_ID" },
    { name: "FIND_ALL_ORDERS" },
    { name: "FIND_ALL_PERMISSIONS" },
    { name: "FIND_ALL_ROLES" },
    { name: "FIND_ALL_USERS" },
]